// <auto-generated />
using Birdsoft.SecuIntegrator24.DataAccessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SecuIntegrator24DAO.Migrations.FinanceDb
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20240806171833_20240806")]
    partial class _20240806
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Birdsoft.SecuIntegrator24.DataAccessObject.MonthlyRevenue", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulativeChangePercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentMonthCumulativeRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentMonthRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastYearCumulativeRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastYearMonthRevenue")
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthOverMonthChangePercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousMonthRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YearOverYearChangePercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "Year", "Month");

                    b.ToTable("MonthlyRevenues");
                });
#pragma warning restore 612, 618
        }
    }
}
